name: Sprint I Test Suite

listeners:
  - extentreportlistener.ExtentReporterNG
  - testngcustomreportlistener.TestNGCustomReportListener
  - util.TestRetryAnalyzerListener

tests:
  - name: I Sprint Test Cases
    classes:
    - testcases.loadpay.broker.BrokerRegisterTest
    - testcases.loadpay.broker.BrokerOutlookTest
    - testcases.loadpay.admin.AdminBrokerTest
    - testcases.loadpay.broker.BrokerLoginTest
    - testcases.loadpay.carrier.CarrierRegisterTest
    - testcases.loadpay.carrier.CarrierOutlookTest
    - testcases.loadpay.admin.AdminCarrierTest
    - testcases.loadpay.carrier.CarrierLoginTest
    - testcases.loadpay.broker.BrokerNewPaymentTest
    - testcases.loadpay.carrier.CarrierNotificationTest
    - testcases.loadpay.carrier.CarrierWireTransferTest
    - testcases.loadpay.carrier.CarrierSameDayACHTest
    - testcases.loadpay.carrier.CarrierNextDAYACHTest
    - testcases.loadpay.carrier.CarrierPayMeNowTabTest
    - testcases.loadpay.broker.BrokerPaymentforUnmatchedCarrierTest
    - testcases.loadpay.unmatched.UnmatchedCarrierRegistrationTest
    - testcases.loadpay.unmatched.UnmatchedCariierEmailVerifyTest
    - testcases.loadpay.unmatched.UnmatchedCarrierAdminTest
    - testcases.loadpay.carrier.CarrierFirstLoginTest
    - testcases.loadpay.unmatched.UnmatchedCarrierSameDayACHTest
    - testcases.loadpay.unmatched.UnmatchedCarrierWireTransferTest